weights: ./runs/exp3/weights/last.pt
cfg: ''
data: ./data/data.yaml
hyp: data/hyp.finetune.yaml
epochs: 500
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 16
world_size: 1
global_rank: -1
